### ISSUE TITLE
`/foo/` does not serve '/foo/index.html`,  `/foo` does not serve `/foo.html`

### ISSUE THREAD

**Issue by rjcorwin** [joehand/hyperdrive-http#43]
Using dat-gateway to browse the web, which depends on hyperdrive-http, we've discovered a couple of path resolutions that websites expect servers to practice that hyperdrive-http does not. For example, see http://gateway.mauve.moe:3000/pfrazee.hashbase.io/ and click on a link on the first link and you'll end up at http://82kzddgmfbk9bf5wzx1jyu2cfeujj7n37718r5unh5pdxe0bubwg.gateway.mauve.moe:3000/blog/universal-publishing-and-the-webs-black-boxes

Now if you add HTML to the end, you'll see it does resolve. http://82kzddgmfbk9bf5wzx1jyu2cfeujj7n37718r5unh5pdxe0bubwg.gateway.mauve.moe:3000/blog/universal-publishing-and-the-webs-black-boxes.html

The other example is if you have a file at `/foo/index.htmlt`, if you try to go to `/foo/` it will not give you `/foo/index.html`.

**Comment by joehand** [comment]
Should be fixed! (though the gateway has changes, so not quite sure)
